name: Verify
on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Lint code
        run: bun run format && bun run lint
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore: format'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: bun run build

  types:
    name: Types
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: bun run build
        
      - name: Check types
        run: bun run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ['bun', 'deno', 'node', 'next', 'vite']

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node
        if: ${{ matrix.type == 'node' }}
        uses: actions/setup-node@v3

      - name: Set up Deno
        if: ${{ matrix.type == 'deno' }}
        uses: denoland/setup-deno@v1

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run tests
        run: bun run test:${{ matrix.type }}